

<div class="page-header">
  <h2 style="font-size: 30px; text-align:left;">Combining multiple SMR or AUTO data files</h2>
  <p>Source code: <a href = "#" style = "color:gray;">kraskura/AnalyzeResp_0</a></p>
  <p>Source page: <a href = "#" style = "color:gray;">kraskura/AnalyzeResp_0</a></p>
</div>


`combine_smr`
<br>
<br>

<h4 style="color:#495057; font-weight: bold;  text-align: left">About</h4>
<ul class="breadcrumb" style="background-color:#fff; border:none; color:#3e3f3a">
  <li><a href="#Arguments">Arguments</a></li>
  <li><a href="#Value">Value</a></li>
  <li><a href="#Details">Details</a></li>
  <li><a href="#Example">Example</a></li>
  <li><a href="#"><i class="fas fa-download"></i>&nbsp; See datafiles on GitHub</a></li>
</ul>


<h4 style="color:#495057; font-weight: bold;  text-align: left">Description</h4>

<!-- <h4 style="color:#495057; font-weight: bold;  text-align: left">Before running the SMR function </h4><br> -->

There may be more than one AUTO file recorded for one respirometry trial. Use this function to combine several files together to then calculate SMR/RMR using all measurement cycle values on one continuous (relative, start with 0 min) timescale.

<h4><a style="color:#495057; font-weight: bold;  text-align: left" name="Arguments">Arguments</a></h4>


  Argument       | Description | Default
---: | :------------- | :---
**smr_files**   | A character vector of _..._analyzed.csv_ . These are output files from `SMR` function. 2 or more files must be specified | --
**date_format** | The date format used in the original FireSting files. Must specify one of the following: `c("m/d/y","d/m/y","y-m-d")` | `"m/d/y"`
**path**        | Specify working directory for all output files. This argument has two options, i) files can be automatically organized in newly created folders, any character may be used, ii) the default is a local directory | `"."` (local directory)


<br><h4><a name="Value" style="color:#495057; font-weight: bold;  text-align: left">Value</a></h4>

<h5 style="color:#495057; font-weight: bold;  text-align: left; text-indent:+10px;"><i class="fas fa-ellipsis-h"></i>&nbsp; Data outputs</h5>

1. *.csv files*
* "(...)_GLUED_nX.csv"
  - The combined file will get a new name tag where X = the N of files. The new file will be saved in two locations: i) the local directory and ii) in the folder "MMR_SMR_AS_EPOC/input_files". 

<br><h4><a name="Details" style="color:#495057; font-weight: bold;  text-align: left">Details</a></h4> <br>

The output can be directly used in the MMR_SMR_AS_EPOC function. The input files are not affected in any manner.

<br><h4><a name="Example" style="color:#495057; font-weight: bold;  text-align: left">Example</a></h4> <br>


<pre class = "sourceCode yaml"> 
# any n files will combine. 

combine_smr(smr_files=c("jun01_2021_box1_smr1_mgO2L_analyzed.csv",
                        "jun01_2021_box1_smr2_mgO2L_analyzed.csv",
                        "jun01_2021_box1_smr3_mgO2L_analyzed.csv"),
            date_format = "m/d/y")
</pre>





