


<div class="page-header">
<h2 style="font-size: 30px; text-align:left;">Functions</h2>

</div>

<div class="well">
All functions are currently compiled in one R script. 
<p> Download here: <a href = "https://github.com/kraskura/AnalyzeResp_0/blob/main/R/AnalyzeResp_0.R" style = "color:gray;">AnalyzeResp_0.R</a></p>

<p style="color:green;  font-weight:bold; text-align: left"> Please note: The function outputs are saved in users local directory </p>

</div>

### Metabolic performance functions

<ul>
  <li><a href="./SMR.html" style = "color:#8e8c84; font-weight:bold;"><code>SMR</code></a>
    <p> Used to analyze O~2~ and temperature data recorded continuously using repeat open(flush):closed(measure) cycles to obtain regressions representative of metabolic rates. Refer to Figure 3 on this information page: <a href ="./about.html" style = "color:gray;">aquatic respirometry</a></p></li>
  <li><a href="./MMR.html" style = "color:#8e8c84; font-weight:bold;"><code>MMR</code></a>
    <p> Used to analyze O~2~ and temperature data recorded to obtain regressions representative of individual's maximum metabolic rate</p></li>
  <li><a href="./MMR_SMR_AS_EPOC.html" style = "color:#8e8c84; font-weight:bold;"><code>MMR_SMR_AS_EPOC</code></a>
    <p> Used to estimate aerobic metabolic performances in animals: MMR, SMR, EPOC (recovery), and Absolute Aerobic Scope. Relies on outputs from SMR and MMR functions</p></li> 
  <li><a href="./SDA_TBD.html" style = "color:#8e8c84; font-weight:bold;"><code>SDA</code></a>
    <p> Used to estimate metabolic performances associated with digestion (SDA refers to digestion costs). Development in progress</p></li>
</ul>


### Setup functions

<ul>
  <li><a href="./organize_MR_analysis.html" style = "color:#8e8c84; font-weight:bold;"><code>organize_MR_analysis</code></a>
    <p> Used to create a collection of local directories that help organizing the analysis by exporting output files to specific folders associated with each metabolic performance function (not required)</p></li> 
  <li><a href="./txt_csv_convert.html" style = "color:#8e8c84; font-weight:bold;"><code>txt_csv_convert</code></a>
    <p> Used to convert and format (strip from unused columns and rows) the raw '.txt' data file to produce a .csv file that is required for `MMR` and `SMR` functions</p></li> 
  <li><a href="./csv_file_split.html" style = "color:#8e8c84; font-weight:bold;"><code>csv_file_split</code></a>
    <p> Used to split one file into 2 separate files, where each newly created file starts with 0 min relative times (e.g., useful when MMR and SMR are recorded in one file)</p></li> 
  <li><a href="./combine_smr.html" style = "color:#8e8c84; font-weight:bold;"><code>combine_smr</code></a>
    <p> Used to combine two files to standardize data on one continuous relative timescale (e.g., useful when one experimental trial has more than one files for SMR overnight measurement) </p></li> 
</ul>


### Additional functions

<ul>
  <li><a href="./sum_backgr.html" style = "color:#8e8c84; font-weight:bold;"><code>sum_backgr</code></a>
    <p> Used to summarizes background respiration rates across multiple trials</p></li> 
</ul>
<ul>
  <li><a href="./convert.o2.Firesting.html" style = "color:#8e8c84; font-weight:bold;"><code>convert.o2.Firesting</code></a>
    <p> Used to convert oxygen units on the file. Relies on `rMR::DO.unit.convert`</p></li> 
</ul>








