

<div class="page-header">
  <h2 style="font-size: 30px; text-align:left;"> Aerobic scope, AS, and excess post exercise oxygen consumption, EPOC </h2>
`MMR_SMR_AS_EPOC`
<br>
</div>


<h4 style="color:#495057; font-weight: bold;  text-align: left">About</h4>
<ul class="breadcrumb" style="background-color:#fff; border:none; color:#3e3f3a">
  <li><a href="#Arguments">Arguments</a></li>
  <li><a href="#Value">Value</a></li>
  <li><a href="#Details">Details</a></li>
  <li><a href="#Example">Example</a></li>
  <li><a href="https://github.com/kraskura/AnalyzeResp_0/tree/main/Test/MMR_SMR_AS_EPOC"><i class="fas fa-download"></i>&nbsp; See datafiles on GitHub</a></li>
</ul>


<h4 style="color:#495057; font-weight: bold;  text-align: left">Description</h4>

The `MMR_SMR_AS_EPOC` function estimates aerobic metabolic capacity metrics: MMR, SMR, absolute aerobic scope, and recovery performances. 

The experimental details of aquatic respirometry are used to obtain the best estimates of aerobic performances. The user provides several key details, including:

+ the volume of the respirometer,
+ the body mass of an individual,
+ background respiration during respirometry trial.

The required input files to this function are generated by `SMR,` and `MMR` function runs.



<h4><a style="color:#495057; font-weight: bold;  text-align: left" name="Arguments">Arguments</a></h4>



  Argument       | Description | Default
---: | :------------- | :---
**data.MMR**             | The name of the MMR data file ("...analyzed.csv "; a character string); an output file from the `MMR` function. When unavailable, enter `"none"` | --
**data.SMR**             | The name of the SMR data file ("...analyzed.csv "; a character string); an output file from the `SMR` function. When unavailable, enter `"none"` | --
**AnimalID**             | Indicates individual ID; must be a vector of 4 characters. When missing, enter `"NA"` | --
**BW.animal**            | Indicates individual mass; must be a vector of 4 characters. When missing, enter `"0"` | --
**resp.V**               | Indicated the volume (L) of respirometer chambers; must be a vector of 4 numbers (e.g., `c(1, 1, 1, 1)`, for four 1-L respirometers) | --
**r2_threshold_smr**     | R^2^ threshold for SMR, measurements below the threshold are excluded | --
**r2_threshold_mmr**     | R^2^ threshold for MMR, measurements below the threshold are excluded | --
**min_length_mmr**       | The duration of MMR steepest slope measurement; 180, 120, 90, 60 seconds (s) | --
**scaling_exponent_mmr** | Body mass scaling exponent to correct MMR values for body size. MR=aBM^b (MR = metabolic rate, BW = body mass, a = scaling coefficient [the intercept], and b = scaling exponent [the power term]) | `1` (isometric scaling)
**scaling_exponent_smr** | body mass scaling exponent to correct SMR values for body size. Same details as above. | 1
**plot_smr_quantile**    | Indicating what percentile lower MO~2~ values to plot; must be 10, 15, or 20 |=`15`, 
**mmr_type**             | Currently an unused argument | `"min"`
**N_Ch**                 | The number of channels of the FireSting. It must be either 4 or 8. | 4
**drop_ch**              | Indicates which channel is dropped or entirely excluded from the analysis. Must be a numerical vector, e.g., c(1,3) | `NULL`
**MLND**                 | Logical argument. If `TRUE`, SMR is estimated also using Mean Lowest Normal Distribution analysis. More details in [Chabot et al 2016](https://doi.org/10.1111/jfb.12845).| `TRUE`
**epoc_threshold**       | Indicates the threshold relevant to an individual's SMR to calculate the end time of recovery (the time at which metabolic rate has returned to `epoc_threshold`). The default is the SMR level (`1`; At 100% SMR). To use 120% SMR as a recovery threshold, enter `epoc_threshold = 1.2`. | 1
**recovMMR_threshold**   | Short-term recovery threshold relevant to individual's MMR. Indicates the (%) level of MMR to calculate recovery indices. The default indicates 50 % MMR, e.g., the time it takes to recover to 50% MMR (default). Enter `0.3` for 30% MMR, `0.8` for 80% MMR) | `0.5`
**end_EPOC_Ch**          | Manually assigned end time (min) of full recovery (EPOC). The time can be assigned for each channel independently; use a numerical vector of 4 variables, one for each channel (e.g., `c(120, 120, NA, 180)`, for 2 h, 2h, SMR level, and 3 h EPOC end times, respectively) | `NA`
**background_prior**     | The name of the analyzed background "...analyzed.csv" file, an output file from the `SMR` function (respiration in an empty respirometer measured before the respirometry trial). | `NA`
**background_post**      | The same as `background_prior`, only post respirometry trial | `NA`
**background_slope**     | Manually assigned background slope used to correct metabolic rate in all individuals. Provide numeric value in mgO~2~ L<sup>-1</sup> h<sup>-1</sup> | `NULL`
**background.V**         | Manually assigned respirometer volumes (L). A vector with 4 numeric variables, one for each channel. | `NULL`
**background_linear_gr** | Logical argument. If `TRUE`, it is be assumed that bacterial growth (thus respiration rates) changed linearly across the duration of the respirometry trial. When `TRUE`, metabolic rate values across the given trial are corrected using the estimated background values from the linear growth curve. Both `background_prior` and `background_post` must be provided to apply this. | `FALSE`
**match_background_Ch**  | Logical. If `TRUE`, the background respiration is estimated and applied channel-specific. The `background_prior` and `background_post` are used to estimate background respiration specific to each channel (or individual), which then is used to correct each individual’s MO~2~ independently. By default, the mean background respiration rate from all channels is calculated and applied to correct all individual's MO~2~ | `FALSE`
**mmr_background**       | Specifies what background value should be used to correct MMR value. Options: i) `"back_prior"` takes background respiration rate value estimated from the `background_prior` file only, ii)` "SAME_slope"` takes background respiration rate value that is applied to the entire trial (MMR and SMR, indistinguishable), and iii) a defined respiration rate value mgO~2~ L<sup>-1</sup> h<sup>-1</sup>. | `SAME_slope`
**path**                 | Defines the directory to save output files. Two options: i) exports are saved in the currently set working directory, or ii) prior-defined directories as created by function `organize_MR_analysis` | `"."` (local directory)
**date_format**          | The date format used in the original FireSting data files. Must specify one of the following: `"m/d/y"`, `"d/m/y"`, `"y-m-d"` | `"m/d/y"`
**mo2_val_for_calc**     | Units of metabolic rates represented on export figures. `mo2_common_mass_kg` (standardized MO~2~ to 1 kg fish using scaling exponents provided); mg O~2~ min<sup>-1</sup> kg<sup>-1</sup>), `mo2_individual_kg` (MO~2~ of the whole individual, mgO~2~ min<sup>-1</sup>) | `"mo2_1kg"`
**common_mass**          | Metabolic performances are often calculated per unit mass. Use this argument to define what standardized mass should be. (default is MO~2~ mgO~2~kg<sup>-1</sup>^ min<sup>-1</sup>^, a common mass of 1 kg). Units = kg | `1`
**spars_levels**         | Select levels of smoothing for the recovery performance (EPOC) estimates. Enter up to 10 values. Passed down to [smooth.spline](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/smooth.spline) | `c(0.1, 0.2, 0.3)`

<br><h4><a name="Value" style="color:#495057; font-weight: bold;  text-align: left">Value</a></h4>

<h5 style="color:#495057; font-weight: bold;  text-align: left; text-indent:+10px;"><i class="fas fa-ellipsis-h"></i>&nbsp; Data outputs</h5>

**".csv files"**

* (...)_analyzed_MMR__EPOC_DATA.csv
  - Directory: MMR_SMR_AS_EPOC/csv_analyzed_EPOC
  - Primary metrics included: Time%MMR, Time to full EPOC, EPOC (total), and hourly EPOC. 
* (...)_MMR_analyzed.csv
  - Directory: MMR_SMR_AS_EPOC/csv_analyzed_MMR
  - Primary (not all) metrics included: 
    + MMR (MO~2~, mgO~2~<sup>-1</sup> min<sup>-1</sup> kg<sup>-1</sup>, and in absolute values mgO~2~ min<sup>-1</sup>
    + temperature at the time of MMR recording 
* (...)_MR_analyzed.csv
  - Directory: MMR_SMR_AS_EPOC/csv_analyzed_MR
- This is one of the most comprehensive files with many key metabolic performances.
  - Primary (not all) metrics included: 
    + **SMR** estimates (mean of lowest ‘q’ quantile, mean on the lowest 10 values after excling the lowest 5 values, mlnd)
    + **Aerobic scopes** using each SMR estimate
    + **Number of MO~2~** values recorded overnight and were used to estimate the SMR (or RMR)
    + **MMR** value
    + **MMR** duration, or length of the MMR recording 
    + **body mass** (kg) of animals
    + **temperature** in ºC, representing the mean for the trial
  
* ()_SMR_analyzed.csv
  - Directory: csv_analyzed_SMR
  - Primary metrics included: estimated MO2 values (MO2, mgO2/min/kg, and in absolute values mgO2/min/ whole animal) for each measurement recorded, temperature for each measurement, **background** associated with each measurement.  
  - Any MO2 values with desired metabolic scaling corrections applied

**".png files"**

* (...)__box4_mmr_analyzed_MMR__Ch2_EPOC_PLOT
  - Directory: MMR_SMR_AS_EPOC/(…)plots_ch_EPOC 
  - Figure with MO~2~ over time. This figure shows the full recovery trend and has printed EPOC estimate values. One plot for each selected smoothing level is plotted (arg: `spar_levels`. Time to X% MMR, and time to full EPOC are indicated
* (...)__box4_smr_analyzed_SMR_PLOT_SMR_methodsALL
  - Directory: MMR_SMR_AS_EPOC/(…)plots_methods_sum_SMR
  - Figure displaying all SMR estimated values (3 different methods). Particularly useful to compare the different SMR estimate values on the same data trends
* (...)__box4_smr_analyzed_SMR_PLOT_SMR_analyses
  - Directory: MMR_SMR_AS_EPOC/(…)plots_min_values_SMR
  - 2-panel figure. 
    + top: all MR values recorded, the lowest 5 values are red, the next lowest is green
    + bottom: the same plot, but lowest 10% (turquoise), 15% (blue) and 20% (purple) values are colored; each % or percentile is used to estimate SMR
* (...)__box4_smr_analyzed_SMR_Ch1_MLND_SMR_analysed
  - Directory: MMR_SMR_AS_EPOC/(…)plots_mlnd_SMR
  - Figure with diagnostic plots associated with the mean lowest normal distribution analysis to obtain SMR value
* (...)__box4_smr_analyzed_SMR_PLOT_BACKGROUND.png
  - only plotted if background files are provided. 
  - Directory: MMR_SMR_AS_EPOC/(…)plots_background
  - Figure showing the estimated bacterial background respiration rates 

<br><h4><a name="Details" style="color:#495057; font-weight: bold;  text-align: left">Details</a></h4> <br>

<h5 style="color:#495057; font-weight: bold;  text-align: left; text-indent:+10px;"><i class="fas fa-ellipsis-h"></i>&nbsp; Support functions</h5>

`EPOC.spar` Arguments: <a style="color:grey"> spar, d,  EPOCdata, mmr.val, epoc_threshold , recovMMR_threshold , newdata.smr, MLND </a>

<br><h5 style="color:#495057; font-weight: bold;  text-align: left; text-indent:+10px;"><i class="fas fa-ellipsis-h"></i>&nbsp; Messages in Console</h5>

- `MMR 1st: 3.72 < MMR overall 3.85`: indicates if any MR value for overnight measurements is greater than the MMR measurement (1st measurement)
- `Ch1: MMR = 3.85`: The value of estimated MMR for each channel/animal
- `EPOC threshold = SMR`: indicates the selected SMR threshold
- `Save MMR, SMR, and MR files`: confirm the files are saved 

<br><h4 style="color:#495057; font-weight: bold;  text-align: left;"> References</h4>

Chabot, D., Steffensen, J.F. and Farrell, A.P. (2016), The determination of standard metabolic rate in fishes. J Fish Biol, 88: 81-121. [https://doi.org/10.1111/jfb.12845](http://doi.wiley.com/10.1111/jfb.12845)


<br><h4><a name="Example" style="color:#495057; font-weight: bold;  text-align: left">Example</a></h4> <br>

<pre class = "sourceCode yaml"> 

# run using defaults, where possible:
MMR_SMR_AS_EPOC( data.MMR = "jul04_2019_opasize_box4_mmr_analyzed.csv",
                 data.SMR = "jul04_2019_opasize_box4_smr_analyzed.csv",
                 AnimalID = c("23-rbred","27-ltred","27-lbred","27-rtred"),
                 BW.animal = c(0.065,0.068,0.061,0.062),
                 resp.V = c(1.890,1.890,1.4475,1.4475),
                 r2_threshold_smr = 0.85,
                 r2_threshold_mmr = 0.9,
                 min_length_mmr = 120)
                 
# parametrized run, no background:
MMR_SMR_AS_EPOC(
        data.MMR = "jul04_2019_opasize_box4_mmr_analyzed.csv",
        data.SMR = "jul04_2019_opasize_box4_smr_analyzed.csv",
        AnimalID = c("FISH1","FISH2","FISH3","FISH4"),
        BW.animal = c(0.065,0.068,0.061,0.062),
        resp.V = c(1.9,1.9,1.5,1.5),
        r2_threshold_smr = 0.85,
        r2_threshold_mmr = 0.9,
        scaling_exponent_mmr = 1,
        scaling_exponent_smr = 1,
        epoc_threshold = 1,
        drop_ch = 1,
        recovMMR_threshold = 0.7,
        plot_smr_quantile=10, 
        mo2_val_for_calc = "mo2_1kg", # "mo2_1kg", mo2_common_mass_kg, mo2_per_individual_kg
        end_EPOC_Ch = c(NA, NA, NA, NA), # must match how many channels are there; use NA otherwise
        min_length_mmr = 120,
        spars_levels = c(0.1, 0.3),
        MLND=TRUE,
        path="foldering",
        date_format = "m/d/y",
        N_Ch = 4, 
        common_mass= 1) # in kg

# run with background respiration. 
MMR_SMR_AS_EPOC(
        data.MMR = "jul04_2019_opasize_box4_mmr_analyzed.csv",
        data.SMR = "jul04_2019_opasize_box4_smr_analyzed.csv",
        AnimalID = c("FISH1","FISH2","FISH3","FISH4"),
        BW.animal = c(0.065,0.068,0.061,0.062),
        resp.V = c(1.9,1.9,1.5,1.5),
        r2_threshold_smr = 0.85,
        r2_threshold_mmr = 0.9,
        scaling_exponent_mmr = 1,
        scaling_exponent_smr = 1,
        epoc_threshold = 1,
        # drop_ch = 1,
        recovMMR_threshold = 0.7,
        plot_smr_quantile=10, 
        mo2_val_for_calc = "mo2_1kg", # "mo2_1kg", mo2_common_mass_kg, mo2_per_individual_kg
        end_EPOC_Ch = c(NA, NA, NA, NA), # must match how many channels are there, use NA otherwise
        # mmr_type = "mean",
        min_length_mmr = 120,
        spars_levels = c(0.1, 0.3),
        background_prior = "jul04_2019_box4_back_pre_dummy_analyzed.csv" ,
        background_post = "jul04_2019_box4_back_post_dummy_analyzed.csv" ,
        background_slope = NULL,
        background.V = NULL,
        MLND=TRUE,
        match_background_Ch = TRUE,
        mmr_background = "SAME_slope",
        background_linear_gr = TRUE,
        path="foldering",
        date_format = "m/d/y",
        N_Ch = 4, 
        common_mass= 1) # in kg

</pre>
