
<div class="page-header">
  <h2 style="font-size: 30px; text-align:left;">Updates and To-Do List</h2>
  <p>Source: <a href = "https://github.com/kraskura/AnalyzeResp_0/blob/main/docs/progressNotes.Rmd" style = "color:gray;">/AnalyzeResp_0/docs/progressNotes.Rmd</a></p>
</div>



**To do list:**

0. Make packgdown, and rework it into an actual package in R. 

1. Improve the naming dependency, take that out. 
2. Add more flexibility of different oxygen units, for example, % air saturation in the local functions.
3. Development of function that estimates hypoxia tolerance, P-crit analysis
4. (?) Temperature in the MMR_SMR_AS_EPOC/csv_analyzed_MR/ data output files is just for the MMR section of the data, needs adjustment. 
5. Add N=xxx in the quantile plots
6. Add FAS analysis
7. Fix units when calculating MO~2~ for either: i) animal (mgO~2~/min/animal) ii) mass-specific, per kg (mO~2~/min/kg), iii) stanadardised mass using scaling 
8. script and demo on how to use our code with non Firesting data files
9. Make one rmd with all files running as entirely reproducible example, consolidate the existing files



#### Updates, for 2022 current version:  


Date| Description | Previous | UPDATE
:--- |  :-------------  | :--- | :---
Feb-Mar 2022 | Update output file ((...analyzed_MR.csv)), previously all AS and MMR_overall were ignored when running the function with argument: `smrfile = "none"` when running the 
Jan 2022 | MMR function arguments, names changed| `Ch1`, `Ch2`, `Ch3`, `Ch4` | `mmr_Ch1`, `mmr_Ch2`, `mmr_Ch3`, `mmr_Ch4` 
Jan 2022 | MMR figure (new), analytical for displaying difference for sliding windows, slope and R^2^|  | 
Jan 2022 | MMR_SMR_AS_EPOC smoothing, fewers trends plotted, new argument for user input| NA  | `spar_levels` & better plot

