



<div class="page-header">
  <h2 style="font-size: 30px; text-align:left;">Converting and reformatting raw text data files</h2>
`txt_csv_convert`
<br>
</div>


<h4 style="color:#495057; font-weight: bold;  text-align: left">About</h4>
<ul class="breadcrumb" style="background-color:#fff; border:none; color:#3e3f3a">
  <li><a href="#Arguments">Arguments</a></li>
  <li><a href="#Value">Value</a></li>
  <li><a href="#Details">Details</a></li>
  <li><a href="#Example">Example</a></li>
  <li><a href="#"><i class="fas fa-download"></i>&nbsp; See datafiles on GitHub</a></li>
</ul>


<h4 style="color:#495057; font-weight: bold;  text-align: left">Description</h4>

The original FireSting datafiles are in ".txt" format and cannot be directly used with our analysis functions.

This function converts ".txt" to a ".csv" file which can be used onwards to carry out an analysis of metabolic performances. This function also forwards only the necessary data that is required for analysis. For example, forwarded are O~2~ level values, temperature, and time stamp, but not the information on probe calibration, pressure metrics, and others. 

<h4><a style="color:#495057; font-weight: bold;  text-align: left" name="Arguments">Arguments</a></h4>

  Argument       | Description | Default
---: | :------------- | :---
**txt_file**    | The name of the original ".txt" file from FireSting | --
**N_Ch**        | The number of FireSting channels. Options include 2, 4, 8. If a 2-channel FireSting was used, this argument could be ignored, or enter `4` | `4`
**path**        | Specify the folder to save created “.csv” data file. If `organize_MR_analysis` was used the options include: `AUTO`, `MANUAL`, `BACTERIAL_RESP`, or `SDA` | `"."` (local directory)

<br><h4><a name="Value" style="color:#495057; font-weight: bold;  text-align: left">Value</a></h4>

Essential step function providing formatted .csv files used in `MMR` and `RMR` functions.

<h5 style="color:#495057; font-weight: bold;  text-align: left; text-indent:+10px;"><i class="fas fa-ellipsis-h"></i>&nbsp; Data outputs</h5>

**.csv files**

- Name: same as the text original ‘.txt’ file, but with '.csv' extension
- Export directory:
  * if `path = "."`, files are saved locally. 
  * if `organize_MR_analysis` was used:
    + ./AUTO/csv_files
    + ./MANUAL/csv_files
    + ./BACTERIAL_RESP/csv_files
    + ./SDA/csv_files
- The transformed '.csv' contains: 
  * computer recorded date,
  * computer recorded time,
  * relative time in seconds (file starts with 0),
  * O~2~ for each channel,
  * temperature. 

<br><h4><a name="Details" style="color:#495057; font-weight: bold;  text-align: left">Details</a></h4> <br>

**Setup tips Related tips:** 

1.	Create a dedicated data analysis folder on the computer.
2.	Place all text files in this folder or working directory.
3.	In script:
    + Run the <a href="./organise_MR_analysis.html" style = "color:#8e8c84; font-weight:bold;"><code>organise_MR_analysis</code></a> function to create new set of local working directories (./AUTO/, ./MANUAL, ./BACTERIAL_RESP). 
    + Then run this function `txt_csv_convert` for each file to be converted while specifying `path = “AUTO”` (or other folder as appropriate).
    + Now, all the text files and newly created directories should be in one parent directory. By specifying `path = "AUTO"` the cleaned up .csv file will be placed in "./AUTO/csv_files", similarly, by indicating `path = "MANUAL"` the cleaned up csv file will be placed in "./MANUAL/csv_files", etc. 
4.	The copies of .txt files can be moved out of the dedicated analysis directory. 

<br><h4><a name="Example" style="color:#495057; font-weight: bold;  text-align: left">Example</a></h4> <br>


<pre class = "sourceCode yaml"> 

# dir() # check the working direcotry setup
 
#  [1] "AUTO"
#  [2] "BACTERIAL_RESP"                   
#  [3] "jul04_2019_opasize_box4_mmr.txt"
#  [4] "jul04_2019_opasize_box4_smr.txt"  
#  [5] "MANUAL" 
#  [6] "MMR_SMR_AS_EPOC"                  
                     
txt_csv_convert(txt_file = "./jul04_2019_opasize_box4_mmr.txt",  path = "MANUAL" , N_Ch = 4)
txt_csv_convert(txt_file = "./jul04_2019_opasize_box4_smr.txt",  path = "AUTO" , N_Ch = 4)
txt_csv_convert(txt_file = "./jul04_2019_opasize_box4_smr.txt",  path = "." , N_Ch = 4) # the converted data (the .csv) files will be saved in the local directory

</pre>
