

<div class="page-header">
  <h2 style="font-size: 30px; text-align:left;">Workshops and events</h2>
  <p>Source: <a href = "https://github.com/kraskura/AnalyzeResp_0/blob/main/docs/workshops.rmd" style = "color:gray;">/AnalyzeResp_0/docs/workshops.rmd</a></p>
</div>

Erika Eliason has hosted and lead two respirometry workshops at UCSB (Oct 25-26 2018, and April 3 2020). The goal of these workshops were to bring together collaborators, students, researchers, postdocs, and others using aquatic respirometry to discuss best practices of of this method experimentally and analytically. 

Below are some of the topics that were covered in our discussions. The complete list is extensive!

\
\

#### Respo retreat @ UCSB, Oct 2018

**Hosted mini-sessions**

- Why do respirometry? Advantages & Limitations 
- How to do field respirometry - learning from each other's mistakes 
- How do we analyze the data? And how can it be incorporated into models?
- Hands on data analysis using an earlier version of AnalyzeResp_0


#### Respo retreat @ UCSB, April 2020

**SMR**

- Why is it beneficial to have low SMR?
  * low energy requirements, eat less
- Why have high SMR?
  * can be positively correlated with higher MMR, boldness, growth rates
  * but these relationships are not super consistent

**RMR? - what is it?**

- Resting _vs_ Routine. Routine is often measured as the average of some period of time. Resting is commonly (not always) a point measurement

**MMR**

- MMR is typically exercise elicited (e.g. swim flumes, chasing by hand with or withour air exposure)
- Can be achieved during digestion 
- What can limit MMR?
- Why is it beneficial to have high MMR?
  * higher performance, e.g. swimming
- But it can be beneficial to have low MMR:
  * don't need to maintain it high

**AS = MMR - SMR**

  - What performances and activities are needed? When to have a large or low AS?
  - Highly ecologically relevant metric
  - Can change across life stages, what drives the changes?

**FAS = MMR/SMR**
  - FAS thresholds as vulnerability indicators

**EPOC!, and more about recovery**

- Recovery from anaerobic exercise, any type anaerobic. Very ecologically relevant!
- The big question is: how much time and resources are needed to recover ENOUGH to return to normal activity, to keep going?
  * Animals likely don't need to recover back to SMR level (and realistically - they likely never do!)
  * We know that fish can fully repeat max swim performance (Ucrit, Umax) with only 45 min recovery 
  * Some important thresholds in ecological physiology: Lactate ~ 10 mmol, MMR50% or MMR75%
  * The plus! don't need an actual SMR measurement 
  * MMR50% may show the first indications of impaired recovery

**Metabolic Scaling**

Three main option to adjust MR to animals body size:

1. Just divide whole animal metabolic rate by body mass to get per unit mass metabolism (e.g. mgO~2~min^-1^kg^-1^, this would be the same as using a scaling exponent of 1 and common mass individual 1kg)
2. Use some common scaling exponent and divide MR by mass^b; b = scaling exponent
3. Estimate scaling from the original data of the study or correct for size otherwise:
    + use residuals from regression models 
    + bring all fish to some mean common body size using existing or estimated sacling exponent
    + use local scaling exponent (what size range is actually enough large to obtain robust estimates?)
- _There are no agreed upon methods to size-correct MR for body size._

**Cleaning to overcome wonky temperature readings and leaky respos (and other sources of messiness!)**

- Measure background 
  * ideally before and after each respirometry trial
- Estimate the error from different potential sources:
  * leaky respos
  * bad temperature readings
  * old oxygen probes
  * technical errors
  * experimental disturbance
  * pumps not flushing right or having some issues
